# GoReleaser configuration for qnap-docker
project_name: qnap-docker

before:
  hooks:
    - go mod tidy
    - make quality-check
    - make test

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    binary: qnap-docker

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

brews:
  - name: qnap-docker
    repository:
      owner: scttfrdmn
      name: homebrew-tap
    homepage: https://github.com/scttfrdmn/qnap-docker
    description: "CLI tool for deploying Docker containers to QNAP NAS devices with Container Station"
    license: MIT
    install: |
      bin.install "qnap-docker"
    test: |
      system "#{bin}/qnap-docker", "--version"